// All 12 keys with diatonic progressions — classic I–IV–V plus secondary chords (ii, iii, vi, etc.)

export const PROGRESSIONS: Record<string, string[][]> = {
  C: [
    ['C', 'F', 'G', 'C'],
    ['C', 'G', 'Am', 'F'],
    ['C', 'Am', 'Dm', 'G'],
    ['C', 'Em', 'F', 'G'],
    ['C', 'Dm', 'F', 'G'],
    ['C', 'Am', 'F', 'G'],
    ['C', 'Em', 'Am', 'F'],
    ['C', 'F', 'Dm', 'G'],
    ['Dm', 'G', 'C'],
    ['C', 'Am', 'F', 'C'],
    // Longer progressions using more chords in the key
    ['C', 'F', 'C', 'G', 'Am', 'F', 'Dm', 'G'],
    ['C', 'G', 'Am', 'F', 'C', 'Dm', 'G', 'C'],
  ],
  Db: [
    ['Db', 'Gb', 'Ab', 'Db'],
    ['Db', 'Ab', 'Bbm', 'Gb'],
    ['Db', 'Bbm', 'Ebm', 'Ab'],
    ['Db', 'Fm', 'Gb', 'Ab'],
    ['Db', 'Ebm', 'Gb', 'Ab'],
    ['Db', 'Bbm', 'Gb', 'Ab'],
    ['Db', 'Fm', 'Bbm', 'Gb'],
    ['Db', 'Gb', 'Ebm', 'Ab'],
    ['Ebm', 'Ab', 'Db'],
    ['Db', 'Bbm', 'Gb', 'Db'],
    ['Db', 'Gb', 'Db', 'Ab', 'Bbm', 'Gb', 'Ebm', 'Ab'],
    ['Db', 'Ab', 'Bbm', 'Gb', 'Db', 'Ebm', 'Ab', 'Db'],
  ],
  D: [
    ['D', 'G', 'A', 'D'],
    ['D', 'A', 'Bm', 'G'],
    ['D', 'Bm', 'Em', 'A'],
    ['D', 'F#m', 'G', 'A'],
    ['D', 'Em', 'G', 'A'],
    ['D', 'Bm', 'G', 'A'],
    ['D', 'F#m', 'Bm', 'G'],
    ['D', 'G', 'Em', 'A'],
    ['Em', 'A', 'D'],
    ['D', 'Bm', 'G', 'D'],
    ['D', 'G', 'D', 'A', 'Bm', 'G', 'Em', 'A'],
    ['D', 'A', 'Bm', 'G', 'D', 'Em', 'A', 'D'],
  ],
  Eb: [
    ['Eb', 'Ab', 'Bb', 'Eb'],
    ['Eb', 'Bb', 'Cm', 'Ab'],
    ['Eb', 'Cm', 'Fm', 'Bb'],
    ['Eb', 'Gm', 'Ab', 'Bb'],
    ['Eb', 'Fm', 'Ab', 'Bb'],
    ['Eb', 'Cm', 'Ab', 'Bb'],
    ['Eb', 'Gm', 'Cm', 'Ab'],
    ['Eb', 'Ab', 'Fm', 'Bb'],
    ['Fm', 'Bb', 'Eb'],
    ['Eb', 'Cm', 'Ab', 'Eb'],
    ['Eb', 'Ab', 'Eb', 'Bb', 'Cm', 'Ab', 'Fm', 'Bb'],
    ['Eb', 'Bb', 'Cm', 'Ab', 'Eb', 'Fm', 'Bb', 'Eb'],
  ],
  E: [
    ['E', 'A', 'B', 'E'],
    ['E', 'B', 'C#m', 'A'],
    ['E', 'C#m', 'F#m', 'B'],
    ['E', 'G#m', 'A', 'B'],
    ['E', 'F#m', 'A', 'B'],
    ['E', 'C#m', 'A', 'B'],
    ['E', 'G#m', 'C#m', 'A'],
    ['E', 'A', 'F#m', 'B'],
    ['F#m', 'B', 'E'],
    ['E', 'C#m', 'A', 'E'],
    ['E', 'A', 'E', 'B', 'C#m', 'A', 'F#m', 'B'],
    ['E', 'B', 'C#m', 'A', 'E', 'F#m', 'B', 'E'],
  ],
  F: [
    ['F', 'Bb', 'C', 'F'],
    ['F', 'C', 'Dm', 'Bb'],
    ['F', 'Dm', 'Gm', 'C'],
    ['F', 'Am', 'Bb', 'C'],
    ['F', 'Gm', 'Bb', 'C'],
    ['F', 'Dm', 'Bb', 'C'],
    ['F', 'Am', 'Dm', 'Bb'],
    ['F', 'Bb', 'Gm', 'C'],
    ['Gm', 'C', 'F'],
    ['F', 'Dm', 'Bb', 'F'],
    ['F', 'Bb', 'F', 'C', 'Dm', 'Bb', 'Gm', 'C'],
    ['F', 'C', 'Dm', 'Bb', 'F', 'Gm', 'C', 'F'],
  ],
  Gb: [
    ['Gb', 'Cb', 'Db', 'Gb'],
    ['Gb', 'Db', 'Ebm', 'Cb'],
    ['Gb', 'Ebm', 'Abm', 'Db'],
    ['Gb', 'Bbm', 'Cb', 'Db'],
    ['Gb', 'Abm', 'Cb', 'Db'],
    ['Gb', 'Ebm', 'Cb', 'Db'],
    ['Gb', 'Bbm', 'Ebm', 'Cb'],
    ['Gb', 'Cb', 'Abm', 'Db'],
    ['Abm', 'Db', 'Gb'],
    ['Gb', 'Ebm', 'Cb', 'Gb'],
    ['Gb', 'Cb', 'Gb', 'Db', 'Ebm', 'Cb', 'Abm', 'Db'],
    ['Gb', 'Db', 'Ebm', 'Cb', 'Gb', 'Abm', 'Db', 'Gb'],
  ],
  G: [
    ['G', 'C', 'D', 'G'],
    ['G', 'D', 'Em', 'C'],
    ['G', 'Em', 'Am', 'D'],
    ['G', 'Bm', 'C', 'D'],
    ['G', 'Am', 'C', 'D'],
    ['G', 'Em', 'C', 'D'],
    ['G', 'Bm', 'Em', 'C'],
    ['G', 'C', 'Am', 'D'],
    ['Am', 'D', 'G'],
    ['G', 'Em', 'C', 'G'],
    ['G', 'C', 'G', 'D', 'Em', 'C', 'Am', 'D'],
    ['G', 'D', 'Em', 'C', 'G', 'Am', 'D', 'G'],
  ],
  Ab: [
    ['Ab', 'Db', 'Eb', 'Ab'],
    ['Ab', 'Eb', 'Fm', 'Db'],
    ['Ab', 'Fm', 'Bbm', 'Eb'],
    ['Ab', 'Cm', 'Db', 'Eb'],
    ['Ab', 'Bbm', 'Db', 'Eb'],
    ['Ab', 'Fm', 'Db', 'Eb'],
    ['Ab', 'Cm', 'Fm', 'Db'],
    ['Ab', 'Db', 'Bbm', 'Eb'],
    ['Bbm', 'Eb', 'Ab'],
    ['Ab', 'Fm', 'Db', 'Ab'],
    ['Ab', 'Db', 'Ab', 'Eb', 'Fm', 'Db', 'Bbm', 'Eb'],
    ['Ab', 'Eb', 'Fm', 'Db', 'Ab', 'Bbm', 'Eb', 'Ab'],
  ],
  A: [
    ['A', 'D', 'E', 'A'],
    ['A', 'E', 'F#m', 'D'],
    ['A', 'F#m', 'Bm', 'E'],
    ['A', 'C#m', 'D', 'E'],
    ['A', 'Bm', 'D', 'E'],
    ['A', 'F#m', 'D', 'E'],
    ['A', 'C#m', 'F#m', 'D'],
    ['A', 'D', 'Bm', 'E'],
    ['Bm', 'E', 'A'],
    ['A', 'F#m', 'D', 'A'],
    ['A', 'D', 'A', 'E', 'F#m', 'D', 'Bm', 'E'],
    ['A', 'E', 'F#m', 'D', 'A', 'Bm', 'E', 'A'],
  ],
  Bb: [
    ['Bb', 'Eb', 'F', 'Bb'],
    ['Bb', 'F', 'Gm', 'Eb'],
    ['Bb', 'Gm', 'Cm', 'F'],
    ['Bb', 'Dm', 'Eb', 'F'],
    ['Bb', 'Cm', 'Eb', 'F'],
    ['Bb', 'Gm', 'Eb', 'F'],
    ['Bb', 'Dm', 'Gm', 'Eb'],
    ['Bb', 'Eb', 'Cm', 'F'],
    ['Cm', 'F', 'Bb'],
    ['Bb', 'Gm', 'Eb', 'Bb'],
    ['Bb', 'Eb', 'Bb', 'F', 'Gm', 'Eb', 'Cm', 'F'],
    ['Bb', 'F', 'Gm', 'Eb', 'Bb', 'Cm', 'F', 'Bb'],
  ],
  B: [
    ['B', 'E', 'F#', 'B'],
    ['B', 'F#', 'G#m', 'E'],
    ['B', 'G#m', 'C#m', 'F#'],
    ['B', 'D#m', 'E', 'F#'],
    ['B', 'C#m', 'E', 'F#'],
    ['B', 'G#m', 'E', 'F#'],
    ['B', 'D#m', 'G#m', 'E'],
    ['B', 'E', 'C#m', 'F#'],
    ['C#m', 'F#', 'B'],
    ['B', 'G#m', 'E', 'B'],
    ['B', 'E', 'B', 'F#', 'G#m', 'E', 'C#m', 'F#'],
    ['B', 'F#', 'G#m', 'E', 'B', 'C#m', 'F#', 'B'],
  ],
}

// Display order: circle of fourths or chromatic
export const KEY_ORDER = ['C', 'Db', 'D', 'Eb', 'E', 'F', 'Gb', 'G', 'Ab', 'A', 'Bb', 'B']
